import { ChatModel } from 'src/api/models/ChatModel';
import { DraftTimeModel } from 'src/api/models/DraftTimeModel';
import { PlayerModel } from 'src/api/models/PlayerModel';

export interface ProMatchFullModel {
  match_id: number;
  barracks_status_dire: number;
  barracks_status_radiant: number;
  chat: ChatModel[];
  cluster: number;
  cosmetics: {};
  dire_score: number;
  draft_timings: DraftTimeModel[];
  duration: number;
  engine: number;
  first_blood_time: number;
  game_mode: number;
  human_players: number;
  leagueid: number;
  lobby_type: number;
  match_seq_num: number;
  negative_votes: number;
  objectives: {};
  picks_bans: {};
  positive_votes: number;
  radiant_gold_adv: {};
  radiant_score: number;
  radiant_win: boolean;
  radiant_xp_adv: {};
  start_time: number;
  teamfights: {};
  tower_status_dire: number;
  tower_status_radiant: number;
  version: number;
  replay_salt: number;
  series_id: number;
  series_type: number;
  radiant_team: {};
  dire_team: {};
  league: {};
  skill: number;
  players: PlayerModel[];
  patch: number;
  region: number;
  all_word_counts: {};
  my_word_counts: {};
  throw: number;
  comeback: number;
  loss: number;
  win: number;
  replay_url: string;
}
